###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: prod
spec:
  template:
    pod:
      eventstreams.production.type: CloudPakForIntegrationProduction
      productID: 2cba508800504d0abfa48a0e2c4ecbe2
      productName: IBM Event Streams
      productVersion: 10.0.0
      productMetric: VIRTUAL_PROCESSOR_CORE
      productChargedContainers: prod-mirror-maker
      cloudpakId: c8b82d189e7545f0892db9ef2731b90d
      cloudpakName: IBM Cloud Pak for Integration
      cloudpakVersion: 2020.2.1
      productCloudpakRatio: "1:1"
  version: 2.5.0
  replicas: 1
  connectCluster: "my-cluster-target"
  clusters:
  - alias: "my-cluster-source"
    bootstrapServers: my-cluster-source-kafka-bootstrap:9092
  - alias: "my-cluster-target"
    bootstrapServers: my-cluster-target-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "my-cluster-source"
    targetCluster: "my-cluster-target"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
