{
 "title": "IBM Event Streams Kafka",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "eventstreams_cluster_name",
    "label": "Cluster Name",
    "query": "label_values(kube_statefulset_labels{namespace=\"$kubernetes_namespace\"}, label_eventstreams_ibm_com_cluster)"
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": "label_values(kube_pod_labels{kubernetes_namespace=\"$kubernetes_namespace\",label_eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",label_app_kubernetes_io_name=\"kafka\"}, label_statefulset_kubernetes_io_pod_name)"
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": "label_values(es_kafka_producermetrics_messageswrittenpertopicperproducer_total_count{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"true\"}[5m]))"
    }
   ]
  },
  { "title": "Filter by Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pod Phase",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "scalar(kube_pod_status_phase{pod=\"$kafka_broker\", phase=\"Failed\"}*1) +  scalar(kube_pod_status_phase{pod=\"$kafka_broker\", phase=\"Pending\"}*2) + scalar(kube_pod_status_phase{pod=\"$kafka_broker\", phase=\"Running\"}*3) +  scalar(kube_pod_status_phase{pod=\"$kafka_broker\", phase=\"Succeeded\"}*4) +scalar(kube_pod_status_phase{pod=\"$kafka_broker\", phase=\"Unknown\"}*5)"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$kubernetes_namespace\",pod=\"$kafka_broker\",container=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "singlestat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\",kubernetes_pod_name=~\"$kafka_broker\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\",kubernetes_pod_name=~\"$kafka_broker\"})"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\",kubernetes_pod_name=~\"$kafka_broker\"})"
    }
   ]
  },
  {
   "title": "Partitions at mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_atminisrpartitioncount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\",kubernetes_pod_name=~\"$kafka_broker\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",eventstreams_ibm_com_discovery=\"\",kubernetes_pod_name=~\"$kafka_broker\"})"
    }
   ]
  },
  { "title": "Broker: $kafka_broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{kubernetes_namespace=\"$kubernetes_namespace\",pod=~\"$kafka_broker\",container=\"kafka\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{kubernetes_namespace=\"$kubernetes_namespace\",pod=~\"$kafka_broker\",container=\"kafka\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_name=\"$eventstreams_cluster_name-kafka\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "singlestat",
   "description": "Total Outgoing Byte Rate",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesinpersec_count{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"}[2m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesoutpersec_count{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kafka_broker\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\"}[2m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  { "title": "Filter by Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(es_kafka_producermetrics_producerequests_total_count{kubernetes_namespace=\"$kubernetes_namespace\",eventstreams_ibm_com_cluster=\"$eventstreams_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[2m]))",
     "legendFormat": "Produce Request Rate"
    }
   ]
  }
 ]
}