###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-admin
  labels:
    app: eventstreams
rules:
  - apiGroups:
      - eventstreams.ibm.com
    resources:
      - eventstreams
      - eventstreams/status
      - kafkatopics
      - kafkatopics/status
      - kafkauser
      - kafkauser/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete