###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: light-insecure
spec:
  license:
    accept: false
    use: CloudPakForIntegrationNonProduction
  version: 10.0.0
  adminApi: {}
  adminUI: {}
  collector: {}
  restProducer: {}
  schemaRegistry:
    storage:
      type: ephemeral
  security:
    internalTls: NONE
  strimziOverrides:
    kafka:
      #      uncomment to enable security
      #      authorization:
      #        type: runas
      replicas: 1
      config:
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
        external:
          type: route
          #          uncomment to enable security
          #          authentication:
          #            type: scram-sha-512
        plain: {}
        tls: {}
      storage:
        type: ephemeral
      metrics: {}
    zookeeper:
      replicas: 1
      storage:
        type: ephemeral
      metrics: {}
