###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: prod-6-brokers
spec:
  version: 10.0.0
  license:
    # By installing this product you accept the license terms at https://ibm.biz/es-license
    accept: false
    use: CloudPakForIntegrationProduction
  adminApi: {}
  adminUI: {}
  collector: {}
  restProducer: {}
  schemaRegistry:
    storage:
      type: persistent-claim
      size: 1Gi
      class: enter-storage-class-name-here
  strimziOverrides:
    kafka:
      replicas: 6
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: "2.5"
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.cleaner.threads: 6
        log.message.format.version: "2.5"
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 6
      listeners:
        external:
          type: route
          authentication:
            type: scram-sha-512
        tls:
          authentication:
            type: tls
      metrics: {}
      resources:
        requests:
          memory: 8096Mi
          cpu: 4000m
        limits:
          memory: 8096Mi
          cpu: 4000m
      storage:
        type: persistent-claim
        size: 50Gi
        class: enter-storage-class-name-here
    zookeeper:
      replicas: 3
      metrics: {}
      storage:
        type: persistent-claim
        size: 4Gi
        class: enter-storage-class-name-here
