###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020, 2022  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: prod-6-brokers
spec:
  version: 11.0.2
  license:
    # By installing this product you accept the license terms at https://ibm.biz/es-license
    accept: false
    use: CloudPakForIntegrationProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 6
      authorization:
        type: custom
        authorizerClass: com.ibm.eventstreams.runas.authorizer.RunAsAuthorizer
        supportsAdminApi: true
      config:
        inter.broker.protocol.version: "3.2"
        log.cleaner.threads: 6
        log.message.format.version: "3.2"
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 6
        default.replication.factor: 3
        min.insync.replicas: 2
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: metrics-config
      resources:
        requests:
          memory: 8096Mi
          cpu: 4000m
        limits:
          memory: 8096Mi
          cpu: 4000m
      storage:
        type: persistent-claim
        size: 50Gi
        class: enter-storage-class-name-here
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: metrics-config
      storage:
        type: persistent-claim
        size: 4Gi
        class: enter-storage-class-name-here
  requestIbmServices:
    iam: true
    monitoring: true
