###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaUser
metadata:
  name: everything
  labels:
    eventstreams.ibm.com/cluster: placeholdercluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Create
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operation: Read
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operation: Alter
